/rm_serial_driver:
  ros__parameters:
    device_name: /dev/ttyUSB0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

    # x2: 1.0    #  x2 对应 x0 x3 对应 x1 a1 对应 a
    # y2: 1.0
    # x3: 1.0
    # y3: 1.0
    # a1: 1.0
    # b1: 1.0


