# you may need to reset the nav points depend on your color
/rm_decision_node:
  ros__parameters:
    home_pose: [ 0.0, 0.0, 0.0 ]

    strategy: 2

    #the area of po
    x_min: 0.0
    x_max: 1.0
    y_min: 0.0
    y_max: 1.0

    Guard_points: [ -0.5, 1.6, 0.0,
              -0.5, 2.4, 0.0,
              -1.0, 2.4, 0.0 ]
    self_addhp_point: [ 0.0, 0.0, 0.0 ]
    self_base_point: [ 0.0, 0.0, 0.0 ]

    S1_Stop_Engineer_point: [ 0.0, 0.0, 0.0 ]
    S1_Stop_Hero_point: [ 0.0, 0.0, 0.0 ]
    S1_Outpost_point: [ 0.0, 0.0, 0.0 ]

    S2_Outpose_point: [ 0.0, 0.0, 0.0 ]

    S3_Patro_points: [ 0.0, 0.0, 0.0,
                          1.0, 2.0, 0.0]

    #will be used if shangpo is not available
    Guard_points2: [0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0]
    po_area1: [-2.0, 1.0, 0.0,
              -2.0, 2.0, 0.0,
              -3.0, 2.0, 0.0,
              -3.0, 1.0, 0.0]
    po_area2: [0.0, -1.0, 0.0,
               1.0, -1.0, 0.0,
               1.0, 1.0, 0.0,
               0.0, 1.0, 0.0]
    po_area3: [200.0, 100.0, 0.0,
              200.0, 200.0, 0.0,
              300.0, 200.0, 0.0,
              300.0, 100.0, 0.0]