/rm_decision_node:
  ros__parameters:
    route1: [-0.5, 1.6, 0.0,
              -0.5, 2.4, 0.0,
             -1.0, 2.4, 0.0]
    route2: [-2.4, 1.0, 0.0,
             -1.7, 1.0, 0.0]
    route3: [-2.475, 1.65, 0.0,
             -2.475, 2.65, 0.0]
    route4: [-2.4, 0.0, 0.0,
             -2.7, 1.0, 0.0]        
    home_pose: [0.0, 0.0, 0.0]
    po_area: [-2.0, 1.0, 0.0,
              -2.0, 2.0, 0.0,
              -3.0, 2.0, 0.0,
              -3.0, 1.0, 0.0]
    po_area2: [-2.0, 1.0, 0.0,
               -2.0, 2.0, 0.0,
               -3.0, 2.0, 0.0,
               -3.0, 1.0, 0.0]
    po_area3: [-2.0, 1.0, 0.0,
              -2.0, 2.0, 0.0,
              -3.0, 2.0, 0.0,
              -3.0, 1.0, 0.0]

