uint8 color

float64 time

uint16 red_1
uint16 red_2
uint16 red_3
uint16 red_4
uint16 red_5
uint16 red_7
uint16 red_outpost_hp
uint16 red_base_hp
    
uint16 blue_1
uint16 blue_2
uint16 blue_3
uint16 blue_4
uint16 blue_5
uint16 blue_7
uint16 blue_outpost_hp
uint16 blue_base_hp

uint16 self_hp
uint16 base_hp


uint32 rfid_status
uint8 event_data
    
   
uint8 supply_robot_id
uint8 supply_projectile_num